### Criando Tabela ###

CREATE TABLE ALUNO_01 (
	MATRICULA 	VARCHAR (11),
    CPF			VARCHAR (11),
    NOME		VARCHAR (30),
    SEXO		VARCHAR (1),
    COD_CURSO	VARCHAR (5)
);

CREATE TABLE CURSO (
	COD_CURSO	VARCHAR (5),
    NOME		VARCHAR (30),
    PRIMARY KEY	(COD_CURSO)
);

CREATE TABLE ALUNO_02 (
	MATRICULA 	VARCHAR (11) NOT NULL,
    CPF			VARCHAR (11) NOT NULL UNIQUE,
    NOME		VARCHAR (30) NOT NULL,
    SEXO		VARCHAR (1) CHECK (SEXO IN('F','M')),
    COD_CURSO	VARCHAR (5),
    PRIMARY KEY (MATRICULA),
    FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO)
);

### Alterando Tabela ###
## Adicionando coluna

ALTER TABLE ALUNO_01
	ADD COLUMN TELEFONE VARCHAR(8) NOT NULL,
    ADD COLUMN EMAIL VARCHAR(30) NOT NULL;

## Adicionando coluna

ALTER TABLE ALUNO_01
	DROP COLUMN TELEFONE;

RENAME TABLE ALUNO_01 TO ESTUDANTE;
RENAME TABLE ESTUDANTE TO ESTUDANTES;